version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file: ./docker.env
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db: